### PR TITLE
Changing themes

### PR DESCRIPTION
**Pull request by Asssket**
Now you can changing themes in real time.
Preview

### CODE REVIEW

**Comment by AlexW00** [comment]
This looks like a cool feature, I like it. However, since I want to keep the start page as simple as possible and the changed theme doesn't persist after reloading the site (since it is static), I am not going to merge this feature.
Maybe I will start working on a V2 of the StartTree homepage, which allows for customization directly on the website and saves state via generating a URL.
Anyway, thank you for this interesting feature!

**Comment by AlexW00** [comment]
Merging into a new branch, I will work on a version that allows live config there (as described above).

**Comment by Asssket** [comment]
Thanks

**Comment by AlexW00** [comment]
Implemented in new version, now live in master branch.

**Pull request merged**
